export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';

export const FETCH_ENUM_VALUES_REQUEST = 'FETCH_ENUM_VALUES_REQUEST';
export const FETCH_ENUM_VALUES_SUCCESS = 'FETCH_ENUM_VALUES_SUCCESS';
export const FETCH_ENUM_VALUES_FAILURE = 'FETCH_ENUM_VALUES_FAILURE';

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';