//Product CRUD
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';

//Fetch enum values
export const FETCH_ENUM_VALUES_REQUEST = 'FETCH_ENUM_VALUES_REQUEST';
export const FETCH_ENUM_VALUES_SUCCESS = 'FETCH_ENUM_VALUES_SUCCESS';
export const FETCH_ENUM_VALUES_FAILURE = 'FETCH_ENUM_VALUES_FAILURE';

//Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const GET_CART = 'GET_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';